### ISSUE TITLE
Following instructions for a clean install does not work

### ISSUE THREAD

**Issue by dave600b** [EHDEN/CdmInspection#37]
Hi, Running remotes::install_github("EHDEN/CdmInspection")

Results in an error of:
Error: Failed to install 'CdmInspection' from GitHub:
(converted from warning) package ‘ROhdsiWebApi’ is not available for this version of R

I'm using R version 4.0.3 (I realise the instructions say R4.0.1 but am hoping that a minor version bump is not causing this issue.)

Just following the instructions and installing as I go.

**Comment by PRijnbeek** [comment]
Could you try to install ROhdsWebApi and try again?

**Comment by scossin** [comment]
We encountered the same error. I think it's a bit confusing if you (@dave600b) are new to the R language because it only means the package was not found on the CRAN website. To install it:

``` r
remotes::install_github("OHDSI/ROhdsiWebApi")
```

Since this is the only package not available on CRAN and this package only uses one function "ROhdsiWebApi::getWebApiVersion" to send a HTTP request to WebAPI, another solution could be to put this function in the CdmInspection package (@PRijnbeek). It's against the "Don't repeat yourself" principle but the package would be easier to install and would have less external dependencies.

**Comment by PRijnbeek** [comment]
Thanks, I will look into that.

**Comment by dave600b** [comment]
Thank you, I will try this tomorrow.
