### ISSUE TITLE
Description contains a blank line

### ISSUE THREAD

**Issue by superbspeed** [EHDEN/CdmInspection#55]
I'm getting an error when I try to add the package into RStudio Package Manager:

```
$ /opt/rstudio-pm/bin/rspm logs --transaction-id=108
2021/02/24 21:31:00.784353461 Error : contains a blank line
2021/02/24 21:31:00.784669645 * checking for file '/tmp/git/DESCRIPTION' ... EXISTS but not correct format
Error running /tmp/ext/timestamper: exit status 1
```

Can you please remove this line from DESCRIPTION?

https://github.com/EHDEN/CdmInspection/blob/776b5dca64e144657de250127255b49ebaf8c8dc/DESCRIPTION#L39

**Comment by PRijnbeek** [comment]
@superbspeed 

Have not seen this before from any of the other data partners that run the code, but it should be removed indeed.

I will push an updated version with that fixed in develop for you to test.

By the way you can always test this yourself by forking the package, making the fix, building the package, test the fix. You could contribute that fix then by doing a pull request to the Dev branch.

I will make the fix now in Master so you can test this.
